#
# Wordless: CI - Travis CI
#
# Copyright (C) 2018-2020  Ye Lei (叶磊)
#
# This source file is licensed under GNU GPLv3.
# For details, see: https://github.com/BLKSerene/Wordless/blob/master/LICENSE.txt
#
# All other rights reserved.
#

language: python

cache: pip

matrix:
  include:
    # Windows
    - name: "Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.8
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    # macOS
    - name: "macOS"
      os: osx
      osx_image: xcode11.3
      language: shell
    # Linux
    - name: "Linux"
      os: linux
      dist: xenial
      python: 3.7

install:
  # Check Python version
  - python3 --version || python --version
  # Install dependencies
  - python3 -m pip install --upgrade pip || python -m pip install --upgrade pip
  - pip3 install --requirement requirements.txt --quiet
  # Download data
  - >-
    python3 downloaders/wl_downloader_ci.py ||
    python downloaders/wl_downloader_ci.py

before_script:
  - cd src

# Run tests
script:
  - travis_wait pytest wl_tests/wl_text/test_sentence_tokenization.py
  - travis_wait pytest wl_tests/wl_text/test_word_tokenization.py
  - travis_wait pytest wl_tests/wl_text/test_word_detokenization.py
  - travis_wait pytest wl_tests/wl_text/test_pos_tagging.py
  - travis_wait pytest wl_tests/wl_text/test_lemmatization.py

  - travis_wait pytest --ignore=wl_tests/wl_text/test_sentence_tokenization.py --ignore=wl_tests/wl_text/test_word_tokenization.py --ignore=wl_tests/wl_text/test_word_detokenization.py --ignore=wl_tests/wl_text/test_pos_tagging.py --ignore=pytest wl_tests/wl_text/test_lemmatization.py
